OrdererOrgs:
  - Name: Orderer
    Domain: dfarmadmin.com
    Specs:
    - Hostname: orderer
PeerOrgs:
  - Name: Dfarmadmin
    Domain: dfarmadmin.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Yngadmin
    Domain: yngadmin.com
    Template:
      Count: 1
    Users:
      Count: 1