version: '2'

networks:
    fabric:

services:
    ca.karnatakam.com:
        image: hyperledger/fabric-ca
        container_name: ca.karnatakam.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.karnatakam.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.karnatakam.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e9040234a6a7605e2ddd12e1309baf2c0f2b55da4db16a2158e0c880263e7853_sk
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ../crypto-config/peerOrganizations/karnatakam.com/ca/:/etc/hyperledger/fabric-ca-server-config
        networks:
            - fabric
    couchdb0:
        container_name: couchdb0
        image: hyperledger/fabric-couchdb
        ports:
            - "5984:5984"
        networks:
            - fabric
    peer0.karnatakam.com:
        extends:
            file: docker-compose-base.yml
            service: peer
        container_name: peer0.karnatakam.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.karnatakam.com:7052
            - CORE_PEER_ID=peer0.karnatakam.com
            - CORE_PEER_ADDRESS=peer0.karnatakam.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dfarmadmin.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.karnatakam.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_LOCALMSPID=KarnatakaMMSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@karnatakam.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@karnatakam.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@karnatakam.com/tls/client.key
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984

        volumes:
            - ../crypto-config/peerOrganizations/karnatakam.com/peers/peer0.karnatakam.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/karnatakam.com/peers/peer0.karnatakam.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/karnatakam.com/users:/var/hyperledger/users
            - ../channel-artifacts/:/var/hyperledger/configs
        extra_hosts:
            - "orderer.dfarmadmin.com:3.137.195.195"
            - "peer0.dfarmadmin.com:3.129.8.65"
            - "peer0.yngadmin.com:3.137.192.134"
        networks:
          fabric:
             aliases:
               - net
        ports:
          - 7051:7051
          - 7053:7053

    cli:
        container_name: cli
        image: hyperledger/fabric-tools
        tty: true
        environment:
          - GOPATH=/opt/gopath
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - CORE_LOGGING_LEVEL=DEBUG
          - CORE_PEER_ID=cli
          - CORE_PEER_ADDRESS=peer0.karnatakam.com:7051
          - CORE_PEER_LOCALMSPID=KarnatakaMMSP
          - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/karnatakam.com/users/Admin@karnatakam.com/msp
          - CORE_CHAINCODE_KEEPALIVE=10
        extra_hosts:
          - "orderer.dfarmadmin.com:3.137.195.195"
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ../../chaincode/:/opt/gopath/src/github.com/
            # - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        depends_on:
          - peer0.karnatakam.com
        networks:
            - fabric
