version: '2'

networks:
    fabric:

services:
  ca.dfarmadmin.com:
        image: hyperledger/fabric-ca
        container_name: ca.dfarmadmin.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.dfarmadmin.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dfarmadmin.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/93ac16b9c971dccca0ff757d3af413624c60a08e50279df9ac59258fbdaac1b1_sk
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ../crypto-config/peerOrganizations/dfarmadmin.com/ca/:/etc/hyperledger/fabric-ca-server-config
        networks:
            - fabric

  couchdb0:
        container_name: couchdb0
        image: hyperledger/fabric-couchdb
#   Uncomment the port mapping if you want to expose the CouchDB service,
#   for example to utilize Fauxton User Interface in dev environments.
        ports:
            - "5984:5984"
        networks:
            - fabric
  peer0.dfarmadmin.com:
        extends:
            file: docker-compose-base.yml
            service: peer
        container_name: peer0.dfarmadmin.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.dfarmadmin.com:7052
            - CORE_PEER_ID=peer0.dfarmadmin.com
            - CORE_PEER_ADDRESS=peer0.dfarmadmin.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.yngadmin.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dfarmadmin.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_LOCALMSPID=DfarmadminMSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@dfarmadmin.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@dfarmadmin.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@dfarmadmin.com/tls/client.key
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984

        volumes:
            - ../crypto-config/peerOrganizations/dfarmadmin.com/peers/peer0.dfarmadmin.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/dfarmadmin.com/peers/peer0.dfarmadmin.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/dfarmadmin.com/users:/var/hyperledger/users
            - ../channel-artifacts/:/var/hyperledger/configs
            - ./backup_peer:/var/hyperledger/production

        extra_hosts:
            - "orderer.dfarmadmin.com:3.139.107.217"
            - "peer0.yngadmin.com:3.137.192.134"
            - "peer0.dfarmdemo.com:18.191.80.83"

        networks:
          fabric:
             aliases:
               - net
        ports:
          - 7051:7051
          - 7053:7053
        depends_on:
          - couchdb0

  cli:
        container_name: cli
        image: hyperledger/fabric-tools
        tty: true
        environment:
          - GOPATH=/opt/gopath
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - CORE_LOGGING_LEVEL=DEBUG
          - CORE_PEER_ID=cli
          - CORE_PEER_ADDRESS=peer0.dfarmadmin.com:7051
          - CORE_PEER_LOCALMSPID=DfarmadminMSP
          - CORE_PEER_TLS_ENABLED=false
          - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dfarmadmin.com/peers/peer0.dfarmadmin.com/tls/server.crt
          - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dfarmadmin.com/peers/peer0.dfarmadmin.com/tls/server.key
          - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dfarmadmin.com/peers/peer0.dfarmadmin.com/tls/ca.crt
          - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dfarmadmin.com/users/Admin@dfarmadmin.com/msp
          - CORE_CHAINCODE_KEEPALIVE=10
        extra_hosts:
          - "orderer.dfarmadmin.com:3.139.107.217"
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ../../chaincode/:/opt/gopath/src/github.com/
            # - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        depends_on:
          - peer0.dfarmadmin.com
        networks:
            - fabric
